//4. talvez campos auxiliares seja muito código.      //vamos tentar propriedades automáticas com private set
//Legal, agora não podemos mais modificar o nome uma vez criado o
objeto.

//Aluno marty = new Aluno("Marty", "McFly", new DateTime(1968, 06, 12));
//marty.Nome = "Biff";
//marty.Sobrenome = "Tannen";
//Error CS0272  The property or indexer 'Aluno.Nome' cannot be used in
//this context because the set accessor is inaccessible